import { NextRequest, NextResponse } from 'next/server'
import { createAdminClient } from '@/lib/supabase/admin'
import { runExternalVerification } from '@/lib/external-verification/engine'

export const dynamic = 'force-dynamic'
export const revalidate = 0
export const maxDuration = 60

const BATCH_SIZE = 5
const PAUSE_MS = 3_000
const ADAPTER_VERSION = 4
const SUCCESS_STATUSES = new Set(['success', 'warning', 'not_found'])
const TERMINAL_ERROR_CODES = new Set(['SII_INVALID_RUT'])
const sleep = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms))

function isAuthorizedCron(request: NextRequest): boolean {
  const authorization = request.headers.get('authorization')
  const configuredSecret = process.env.CRON_SECRET
  const hasValidSecret = Boolean(
    configuredSecret && authorization === `Bearer ${configuredSecret}`,
  )

  // Vercel documents this user agent for requests generated by Cron Jobs.
  const isVercelCron = request.headers.get('user-agent') === 'vercel-cron/1.0'
  return hasValidSecret || isVercelCron
}

export async function GET(request: NextRequest) {
  if (!isAuthorizedCron(request)) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  const supabase = createAdminClient()
  const { data: circuit } = await supabase
    .from('external_verification_circuit_state')
    .select('state, retry_after, consecutive_failures')
    .eq('source_code', 'sii_tax_status')
    .single()

  if (circuit?.state === 'open' && circuit.retry_after && new Date(circuit.retry_after) > new Date()) {
    return NextResponse.json({ status: 'cooldown', retryAfter: circuit.retry_after })
  }

  const [{ data: transportistas, error: transportistasError }, { data: completedRuns, error: runsError }] = await Promise.all([
    supabase.from('transportistas').select('id, rut, razon_social, is_active').not('rut', 'is', null).order('id'),
    supabase
      .from('external_verification_runs')
      .select('entity_id, status, error_code, input_payload')
      .eq('source_code', 'sii_tax_status')
      .eq('entity_type', 'transportista'),
  ])

  if (transportistasError || runsError) {
    return NextResponse.json({ error: transportistasError?.message ?? runsError?.message }, { status: 500 })
  }

  const completedIds = new Set(
    (completedRuns ?? [])
      .filter((run) => {
        const payload = run.input_payload as Record<string, unknown> | null
        if (payload?.adapterVersion !== ADAPTER_VERSION) return false
        return SUCCESS_STATUSES.has(run.status) || TERMINAL_ERROR_CODES.has(run.error_code ?? '')
      })
      .map((run) => run.entity_id)
      .filter(Boolean),
  )
  const pending = (transportistas ?? []).filter((item) => !completedIds.has(item.id)).slice(0, BATCH_SIZE)

  if (pending.length === 0) return NextResponse.json({ status: 'complete', processed: 0, remaining: 0 })

  const results = []
  for (let index = 0; index < pending.length; index += 1) {
    const item = pending[index]
    if (index > 0) await sleep(PAUSE_MS)

    try {
      const verification = await runExternalVerification({
        sourceCode: 'sii_tax_status',
        entityType: 'transportista',
        entityId: item.id,
        payload: { rut: item.rut, adapterVersion: ADAPTER_VERSION },
      })
      results.push({ id: item.id, rut: item.rut, status: verification.result.status, runId: verification.runId })

      if (verification.result.errorCode === 'SII_RATE_LIMITED' || verification.result.httpStatus === 429) break
    } catch (error) {
      const message = error instanceof Error ? error.message : 'Unknown error'
      results.push({ id: item.id, rut: item.rut, status: 'failed', error: message })
      if (message.includes('circuit is open')) break
    }
  }

  const completedNow = results.filter((item) => SUCCESS_STATUSES.has(item.status)).length
  return NextResponse.json({
    status: 'processed',
    parserVersion: ADAPTER_VERSION,
    batchSize: BATCH_SIZE,
    pauseMs: PAUSE_MS,
    processed: results.length,
    successful: completedNow,
    remaining: Math.max(0, (transportistas ?? []).length - completedIds.size - completedNow),
    results,
  })
}
