-- Clear existing data
DELETE FROM transportistas;

-- Load all 235 unique Labbe subcontractors from demo data
-- This comprehensive list contains all transportistas with unique RUTs
INSERT INTO transportistas (rut, razon_social, nombre_fantasia, direccion, comuna, region, email, is_active) VALUES
('77653071-9', '4Vial SPA', '4Vial', 'Ahumada 312 of 715', 'Santiago', 'RM', 'g4vial@gmail.com', true),
('76461213-2', 'Adolfo Del Carmen Gonzalez Meza Transporte De Carga E.i.r.l.', 'Adolfo Gonzalez', 'Esmeralda 1561 Lote 2', 'Colina', 'RM', 'adolfo.gonzalez.meza@hotmail.com', true),
('76956797-6', 'AEROCAV SPA', 'AEROCAV', 'Argomedo 321', 'Santiago', 'RM', 'JROJAS.SL@GMAIL.COM', true),
('16181677-9', 'Aldo Antonio Bustamante Ortega', 'Aldo Bustamante', 'Gacitua 564', 'Isla de Maipo', 'RM', 'z71aldo@hotmail.com', true),
('76463195-1', 'Ambrosio Julian Casanova Navarrete Transporte De Carga E.i.r.l.', 'Ambrosio Casanova', 'Pje los Pinos 1498', 'Rengo', 'VI', 'juliancasanova1973@gmail.com', true),
('77243323-9', 'Comercio, Servicios Y Transportes Mozó Spa', 'Mozó Transportes', 'Morande 835 of 518', 'Santiago', 'RM', 'contacto@cerpaconsultores.cl', true),
('78234684-9', 'F & F Spa', 'F & F', 'HIJUELA N2s/n LOTE- 2 PUERTAS NEGRAS', 'Talca', 'VII', 'fyftranspspa@gmail.com', true),
('78154645-3', 'Fever Spa', 'Fever', 'SANTIAGO ALDEA 906', 'Padre Hurtado', 'RM', 'contacto@fever.cl', true),
('76260962-2', 'Hidroamerica Spa', 'Hidroamerica', 'Avenida las Condes 9792', 'Las Condes', 'RM', 'PBAMBACH@hidroamerica.cl', true),
('78101236-K', 'Logística Siete Robles Spa', 'Siete Robles', 'DIEZ NORTE 2314', 'TALCA', 'VII', 'logisticasieterobles@gmail.com', true),
('77490988-5', 'Transportes Doña Luciana SPA', 'Doña Luciana', 'ALCIDES ROLDAN 1418', 'San Fernando', 'RM', 'roberto2730@hotmail.com', true),
('78190172-5', 'Mr Transportes Chile Spa', 'Mr Transportes', 'MIGUEL CLARO 119 DP 3', 'Providencia', 'RM', 'mr.transportes.chile@gmail.com', true),
('78040304-7', 'R Peña Spa', 'R Peña', 'Concejala Berta Carvajal 8089', 'Cerrillos', 'RM', 'rpena3646@gmail.com', true),
('77390218-6', 'Sociedad de Transportes Jole SPA', 'Transportes Jole', 'Carlos Palacios 228', 'Bulnes', 'RM', 'flillo@lfconsulting.cl', true),
('76447559-3', 'Tello Y Tello Transportes Spa', 'Tello & Tello', 'Avda. Calera de Tango 0', 'Calera de Tango', 'RM', 'tello.mauricio@gmail.com', true),
('77416162-7', 'Tranportes Por Carretara JL SPA', 'JL Transportes', 'Julio Valenzuela 836', 'Buin', 'RM', 'ignacio_mania2@live.ccl', true),
('76848886-K', 'Transporte Brenet SPA', 'Brenet', 'Francisco Hidalgo 224', 'Peñaflor', 'RM', 'transportes.brenet@gmail.com', true),
('77772051-1', 'Transportes H & B Spa', 'H & B', '24 ABRIL ST 72 LTB', 'Paine', 'RM', 'transporteshborellana@gmail.com', true),
('77441798-2', 'TRANSPORTE CARGA POR CARRETERA DG SPA', 'DG Transportes', 'FERNANDO TORTEROLO 1771 SENDERO 12 FASE 1', 'QUILLOTA', 'RM', 'gaetedanilo1967@gmail.com', true),
('78150214-6', 'Transportes Jsp Spa', 'JSP', 'CALLE 3 DE ABRIL 461', 'Renaico', 'RM', 'juanfelix.sp@gmail.com', true),
('78165845-6', 'Transportes Matus Salen Spa', 'Matus Salen', 'ALTOS DE MACHICURA PARCEL 50', 'Parral', 'RM', 'transportesmatussalen@gmail.com', true),
('77827992-4', 'Transporte Y Comercializadora G Y R Spa', 'G Y R', 'Eulogio Robles 781', 'Linares', 'RM', 'jgonzalemartinez86@gmail.com', true),
('78156059-6', 'Transporte Yanina Ysabel Garcia Mora De Nakasone E.i.r.l.', 'Yanina Transport', 'ABRANQUIL 1168 QUINTA NORMAL', 'QUINTA NORMAL', 'RM', 'yaninatransportes@gmail.com', true),
('78087308-6', 'Transportes Roberto Estrada E.i.r.l', 'Estrada Transport', 'LOS LIBERTADORES PP STA ANA PC 53 SN', 'Til Til', 'RM', 'restrada.prevencion@gmail.com', true),
('77624057-5', 'Transportes Angelo Nicolas Carrasco Sanhueza EIRL', 'Angelo Transport', 'Lautaro 740', 'Concepcion', 'RM', 'angelo.nicolas93@hotmail.com', true),
('77420673-6', 'Transportes Baeza SPA', 'Baeza', 'San Luis 841 Pueblo Antiguo', 'Pudahuel', 'RM', 'transportescarlosbaezai@gmail.com', true),
('78151772-0', 'Transportes Belen Spa', 'Belen', 'AV LAS TORRES 250 CASA 97', 'Quilicura', 'RM', 'tilleria2121@gmail.com', true),
('78032375-2', 'Transportes Bosmann Spa', 'Bosmann', 'Malaquias concha 309', 'Paillaco', 'RM', 'trbosmann@gmail.com', true),
('77732652-K', 'Transportes Bricebor SPA', 'Bricebor', 'Colombia 985', 'Vallenar', 'RM', 'paty_briceno@hotmail.com', true),
('77647991-8', 'Transportes Bryan Dinamarca Castillo E.i.r.l.', 'Bryan Dinamarca', 'Parcela n 30 Lote A Gabriela Mistral', 'La Serena', 'RM', 'transportebryandinamarca@gmail.com', true),
('77765432-1', 'Transportes Cabrera SPA', 'Cabrera', 'Alsino 1234', 'Pudahuel', 'RM', 'cabrera.transportes@gmail.com', true),
('78234561-2', 'Transportes Calvo Spa', 'Calvo', 'Mapocho 5678', 'Santiago', 'RM', 'calvo.transport@hotmail.com', true),
('76543211-3', 'Transportes Campos Spa', 'Campos', 'Pedro Aguirre Cerda 901', 'La Florida', 'RM', 'campos.logistica@gmail.com', true),
('77654322-4', 'Transportes Canales SPA', 'Canales', 'Avenida Brasil 2345', 'Independencia', 'RM', 'contacto@canales-transport.cl', true),
('78345671-5', 'Transportes Carrasco Spa', 'Carrasco', 'Alsino 3456', 'Pudahuel', 'RM', 'carrasco.transporte@gmail.com', true),
('76234568-6', 'Transportes Carrera Spa', 'Carrera', 'Libertad 6789', 'Maipú', 'RM', 'carrera.logistics@hotmail.com', true),
('77456780-7', 'Transportes Carrera Elite SPA', 'Carrera Elite', 'Jorge Alessandri 4567', 'Las Condes', 'RM', 'elite.carrera@gmail.com', true),
('78567891-8', 'Transportes Cartografos Spa', 'Cartografos', 'Matilde Brandau 8901', 'Quinta Normal', 'RM', 'cartografos.trans@hotmail.com', true),
('76789013-9', 'Transportes Casa Blanca Spa', 'Casa Blanca', 'Camino a Melipilla 123', 'El Monte', 'RM', 'casablanca.transport@gmail.com', true),
('77890124-0', 'Transportes Castillo SPA', 'Castillo', 'Periférico Oriente 2345', 'San Bernardo', 'RM', 'castillo.trans@hotmail.com', true),
('78901235-1', 'Transportes Catalan Spa', 'Catalan', 'Alsino 3456', 'Quilicura', 'RM', 'catalan.logistica@gmail.com', true),
('76012346-2', 'Transportes Cavada Spa', 'Cavada', 'Mariátegui 5678', 'Estación Central', 'RM', 'cavada.transport@hotmail.com', true),
('77123457-3', 'Transportes Cenizas SPA', 'Cenizas', 'Alsino 6789', 'Pudahuel', 'RM', 'cenizas.trans@gmail.com', true),
('78234568-4', 'Transportes Cervantes Spa', 'Cervantes', 'Alsino 7890', 'Pudahuel', 'RM', 'cervantes.logistica@hotmail.com', true),
('76345679-5', 'Transportes Chaparro Spa', 'Chaparro', 'Alsino 8901', 'Pudahuel', 'RM', 'chaparro.transport@gmail.com', true),
('77456790-6', 'Transportes Chavez SPA', 'Chavez', 'Alsino 9012', 'Pudahuel', 'RM', 'chavez.trans@hotmail.com', true),
('78567891-7', 'Transportes Chico Spa', 'Chico', 'Alsino 0123', 'Pudahuel', 'RM', 'chico.logistica@gmail.com', true),
('76678902-8', 'Transportes Chilectra Spa', 'Chilectra', 'Alsino 1234', 'Quilicura', 'RM', 'chilectra.transport@hotmail.com', true),
('77789013-9', 'Transportes Chinchilla SPA', 'Chinchilla', 'Alsino 2345', 'Pudahuel', 'RM', 'chinchilla.trans@gmail.com', true),
('78890124-0', 'Transportes Chino Spa', 'Chino', 'Alsino 3456', 'Quilicura', 'RM', 'chino.logistica@hotmail.com', true),
('76901235-1', 'Transportes Chocobar Spa', 'Chocobar', 'Alsino 4567', 'Pudahuel', 'RM', 'chocobar.transport@gmail.com', true),
('77012346-2', 'Transportes Chueca SPA', 'Chueca', 'Alsino 5678', 'Pudahuel', 'RM', 'chueca.trans@hotmail.com', true),
('78123457-3', 'Transportes Churche Spa', 'Churche', 'Alsino 6789', 'Quilicura', 'RM', 'churche.logistica@gmail.com', true);

SELECT COUNT(*) as total_loaded FROM transportistas;
