-- Load ALL 234 subcontratistas from CSV 45
-- This inserts all records from the CSV into the subcontratistas table

INSERT INTO subcontratistas (rut, razon_social, nombre_contacto, direccion, comuna, is_active) VALUES
('77653071-9', '4Vial SPA', 'Ruben Marchant Needhan', 'Ahumada 312 of 715', 'Santiago', true),
('76461213-2', 'Adolfo Del Carmen Gonzalez Meza Transporte De Carga E.i.r.l.', 'Adolfo Gonzalez Meza', 'Esmeralda 1561 Lote 2', 'Colina', true),
('76956797-6', 'AEROCAV SPA', 'JOSE MIGUEL ROJAS URBINA', 'Argomedo 321', 'Santiago', true),
('16181677-9', 'Aldo Antonio Bustamante Ortega', 'Aldo Antonio Bustamante Ortega', 'Gacitua 564', 'Isla de Maipo', true),
('76463195-1', 'Ambrosio Julian Casanova Navarrete Transporte De Carga E.i.r.l.', 'Ambrosio Casanova Naavarrete', 'Pje los Pinos 1498', 'Rengo', true),
('77243323-9', 'Comercio, Servicios Y Transportes Mozo Spa', 'Falcon Nicolas Mozo Farfan', 'Morande 835 of 518', 'Santiago', true),
('78234684-9', 'F & F Spa', 'Francisco Andres Villagran Ramirez', 'HIJUELA N2s/n LOTE- 2 PUERTAS NEGRAS', 'Talca', true),
('78154645-3', 'Fever Spa', 'MANUEL ESTEBAN CASTAÑEDA CORNEJO', 'SANTIAGO ALDEA 906', 'Padre Hurtado', true),
('76260962-2', 'Hidroamerica Spa', 'Patricio Roberto Bambach Ugarte', 'Avenida las Condes 9792', 'Las Condes', true),
('78101236-K', 'Logística Siete Robles Spa', 'PATRICIO AURELIO RIVAS PUENTES', 'DIEZ NORTE 2314', 'TALCA', true),
('77490988-5', 'Transportes Doña Luciana SPA', 'ROBERTO REBOLLEDO LABRAÑA', 'ALCIDES ROLDAN 1418', 'San Fernando', true),
('78190172-5', 'Mr Transportes Chile Spa', 'MARIA DE LOS ANGELES SOLAR VARGAS', 'MIGUEL CLARO 119 DP 3 NULL', 'Providencia', true),
('78040304-7', 'R Peña Spa', 'Rodrigo Elias Peña Castillo', 'Concejala Berta Carvajal 8089', 'Cerrillos', true),
('77390218-6', 'Sociedad de Transportes Jole SPA', 'Juan Octavio Lillo Espinoza', 'Carlos Palacios 228', 'Bulnes', true),
('76447559-3', 'Tello Y Tello Transportes Spa', 'Mauricio Esteban Tello Reyes', 'Avda. Calera de Tango 0', 'Calera de Tango', true),
('77416162-7', 'Tranportes  Por Carretara  JL SPA', 'Juan Lopez Reyes', 'Julio Valenzuela 836', 'Buin', true),
('76848886-K', 'Transporte Brenet SPA', 'Luz Betsabet Alfaro Brenet', 'Francisco Hidalgo 224', 'Peñaflor', true),
('77772051-1', 'Transportes H & B Spa', 'Daniel Esteban Orellana Muñoz', '24 ABRIL ST 72 LTB', 'Paine', true),
('77441798-2', 'TRANSPORTE CARGA POR CARRETERA DG SPA', 'DANILO ENRIQUE GAETE FUENZALIDA', 'FERNANDO TORTEROLO 1771 SENDERO 12 FASE 1', 'QUILLOTA', true),
('78150214-6', 'Transportes Jsp Spa', 'Juan Felix Saez Paredes', 'CALLE 3 DE ABRIL 461', 'Renaico', true),
('78165845-6', 'Transportes Matus Salen Spa', 'Fabian Corona Figueroa', 'ALTOS DE MACHICURA PARCEL 50', 'Parral', true),
('77827992-4', 'Transporte Y  Comercializadora G Y R Spa', 'Yosselin Elizabeth Reyes Garrido', 'Eulogio Robles 781', 'Linares', true),
('78156059-6', 'Transporte Yanina Ysabel Garcia Mora De Nakasone E.i.r.l.', 'Yanina Ysabel Garcia de Nakasone', 'ABRANQUIL 1168 NULL QUINTA NORMAL', 'QUINTA NORMAL', true),
('78087308-6', 'Transportes Roberto Estrada E.i.r.l', 'Roberto Andrés Estrada Riquelme', 'LOS LIBERTADORES PP STA ANA PC 53 SN NULL', 'Til Til', true),
('77624057-5', 'Transportes Angelo Nicolas Carrasco Sanhueza EIRL', 'Angelo Carrasco Sanhueza', 'Lautaro 740', 'Concepcion', true),
('77420673-6', 'Transportes Baeza SPA', 'Carlos Alberto Baeza Infante', 'San Luis 841 Pueblo Antiguo', 'Pudahuel', true),
('78151772-0', 'Transportes Belen Spa', 'HUGO DEMECIO TILLERIA HUECHE', 'AV LAS TORRES 250 CASA 97 NULL', 'Quilicura', true),
('78032375-2', 'Transportes Bosmann Spa', 'Antonio Bosmann Soto', 'Malaquias concha 309', 'Paillaco', true),
('77732652-K', 'Transportes Bricebor SPA', 'Patricia Briceño Paez', 'Colombia 985', 'Vallenar', true),
('77647991-8', 'Transportes Bryan Dinamarca Castillo E.i.r.l.', 'Bryan Willian Dinamarca Castillo', 'Parcela n 30 Lote A Gabriela Mistral', 'La Serena', true),
('77625968-3', 'Transportes Cale SPA', 'Hugo Núñez Toro', 'Villa los Castaños sitio 12', 'Curico', true),
('77664223-1', 'Transportes Cardenas  Limitada', 'Oscar Alberto Cardenas Rojas', 'M Larrain 1154 BL 7 A DP Rolando Alarcon 0', 'Talagante', true),
('76494991-9', 'Transportes Carlos Marcelo Rebolledo Rojas Eirl', 'Carlos Marcelo Rebolledo Rojas', 'Olegario Lazo 371', 'San Fernando', true),
('77536347-9', 'Transportes Chocobar Spa', 'WILSON HERNAN CHOCOBAR VASQUEZ', 'OSORNO 850 MZ 101 LT 19 TIERRAS BLANCAS', 'Coquimbo', true),
('76518447-9', 'Transportes De Carga Jocelyn Carolina Silva Rojas Eirl', 'Jocelyn Carolina Silva Rojas', 'Barrales 234', 'Melipilla', true),
('78029819-7', 'Transportes Doble Jj Spa', 'Israel Ariel Pradenas Piñeiro', 'Jose Leyan 1228', 'Talagante', true),
('77401369-5', 'Transportes Domingo Alberto Cerda Lagos E.i.r.l.', 'Domingo Cerda Lagos', 'Dr. Adan Henriquez S 03991', 'San Fernando', true),
('77822803-3', 'TRANSPORTES FELIPE ANDRÉS SARRIA JIMÉNEZ E.I.R.L.', 'FELIPE ANDRES SARRIA JIMENEZ', 'AV. SAN LUIS 15 -- 76 CS 76 BARRIO EL ALBA 4', 'Lampa', true),
('76994334-K', 'Transportes Fernando Patricio Valdes Silva Eirl', 'Fernando Patricio Valdes Silva', 'Las Azucenas 1994', 'Santiago', true),
('77624569-0', 'TRANSPORTES IVAN ALFONSO DIAZ RIVAS EIRL', 'Ivan Diaz Rivas', 'Avda Costanera 1174', 'San Pedro de la Paz', true),
('77941312-8', 'TRANSPORTES J&F SPA', 'Daniel Esteban Orellana Muñoz', '24 de Abril St 72 lt b', 'Paine', true),
('78244173-6', 'Transportes Jme Spa', 'John Francisco Jofre Gomez', 'LOS FLAMENCOS 965 MEDIA HACIENDA NULL', 'Ovalle', true),
('78165268-7', 'Transportes Jq Spa', 'Jhon Sebastian Quiroga Esparza', 'PJE VALLE DEL SOL PNTE 2122 PQUE EL SOL NULL PADRE HURTADO', 'PADRE HURTADO', true),
('77503624-9', 'Transportes Jrm E Hijos Limitada', 'Jimena Andrea Herminia Molinet Lillo', 'Pje santa cruz 721, villa larqui', 'Bulnes', true),
('78351383-8', 'Transportes L.y. R Spa', 'JUAN CARLOS LOPEZ DIAZ', 'HERMANO DOMINGO 01485 HNOS DE LA SALLE NULL 01485', 'Puente alto', true),
('77889348-7', 'Transportes Mad Spa', 'Hector Rene Ortiz Gonzalez', 'PSJ LOS MANIOS 2022', 'TALCA', true),
('78113086-9', 'Transportes Maxsu Limitada', 'ROBERTO EUGENIO SUAREZ LOPEZ', 'LA ATAJADA 645 EL RODEO', 'HUECHURABA', true),
('77531127-4', 'TRANSPORTES MICHELL ALEXANDER BRAVO ARAYA E.I.R.L', 'Michell Alexander Bravo Araya', 'Casma 634', 'San Miguel', true),
('77896328-0', 'Transportes Ms Spa', 'Felipe Francisco Miranda Amaya', 'VOLCAN EL MIRADOR 189 SAN ENRIQUE', 'Quilicura', true),
('76891488-5', 'Transportes Myz Spa', 'Oscar Martinez Arriagada', 'San Antonio 385', 'Santiago', true),
('78310280-3', 'Transportes Olmo Vega Spa', 'HUGO CAMILO OLMOS VEGA', 'RIO COPIAPÓ 9558', 'Pudahuel', true),
('78232853-0', 'Transportes Punolaf Lopez Spa', 'Segundo German Punolaf Queupumil', 'AGUSTINAS 1442 DP 402 NULL', 'Santiago', true),
('77287076-0', 'Transportes Rene Ernesto Quiroz Rosales E.i.r.l.', 'Rene Ernesto Quiroz Rosales', 'Lucero del Alba St48 V', 'Calera de Tango', true),
('77016329-3', 'Transportes Ruben Hernan Silva Vasquez E.i.r.l', 'Ruben Hernan Silva Vasquez', 'Monjitas 550', 'Santiago', true),
('77893331-4', 'TRANSPORTES SERGIO SIMONCELLI E.I.R.L', 'Sergio Manuel Simoncelii Rey', 'Gran Avenida 4697 depto 1614', 'San Miguel', true),
('77325414-1', 'Transportes Suyai Spa', 'NICOLE CAROLINA CASTRO MUNOZ', 'SOFIA CARMONA 051 DP 401 G SOFIA TRES G 401', 'La Granja', true),
('76970026-9', 'TRANSPORTES TRANS-LYON SPA', 'Marcelo Eduardo León Salvatierra', 'Caleta Buena 9413, Campo Verde', 'La Florida', true),
('78259175-4', 'Transportes Verpo Spa', 'Manuel Humberto Poza Torres', '4 NORTE 265 C 195', 'San Pedro de la paz', true),
('77926368-1', 'TRANSPORTES WEREK SPA', 'Rene Ignacio Henriquez Rivas', 'Psje los Manios 2022, Barrio la Foresta', 'Talca', true),
('77920451-0', 'TRANSPORTES Y LOGISTICA SERPA SPA', 'Sergio Antonio Figueroa Pinochet', 'Mario Bahamonde 7865', 'San Pedro de la Paz', true),
('78099193-3', 'Transportes Yuyo Spa', 'Raul Abraham Pena Calabrano', 'Pje Pasadena 1000 MZ 2 LT 3', 'Los Angeles', true),
('77806154-6', 'ZF TRANSPORTES SPA', 'Eduardo Andres Zuñiga Luengo', 'San Antonio Lt2 a', 'Linares', true),
('78032949-1', 'CLASSIC TRUCK TRANSPORT SPA', 'JOSE DAVID ESPINOZA CASTRO', 'CAMINO PAINE LONQUEN 4837 ST 1 -B LT D BUIN', 'Santiago', true),
('7321424-6', 'Fernando del Carmen Araya Araya', 'Fernando Del Carmen Araya Araya', 'Lago Ranco Nº734 Villa Los Lagos', 'Panguipulli', true),
('77492287-3', 'Lar Spa', 'Luis Angel Rodriguez Chacon', 'Pasaje Chonos 1376', 'Conchali', true),
('77007552-1', 'Sociedad De Transportes Km Limitada', 'Luis Hernan Iturriaga Barahona', 'Corregidor de Calca 1116 Pedro de Oña', 'Isla De Maipo', true),
('76491308-6', 'Sociedad De Transportes Y Servicios Moreno Y Lopez Limitada', 'Leonardo Antonio Moreno Medina', 'Pasaje Parque Los Ciprece 2841, Nueva Vida', 'Alto Hospicio', true),
('77435776-9', 'Transporte De Carga Jose Rodrigo Burgos Muñoz E.i.r.l.', 'Jose Rodrigo Burgos Muñoz', 'La Estrella 1070', 'Pudahuel', true),
('76303728-2', 'Transporte De Carga Por Carretera Juan Carlos Araya Rodriguez Eirl', 'Juan Carlos Araya Rodriguez', 'Avda Jorge Giacaman Nº122, Villa San Ramon Palomares', 'Lampa', true),
('76902431-k', 'Transporte De Carga Por Carretera Rudy David Mora Morales Eirl', 'Rudy David Mora Morales', 'Las Carabelas # 2002 Villa 5º Centenario', 'Mariquina', true),
('77856341-K', 'Transporte De Carga Raul Erasmo Chandia  Zuñiga E.i.r.l.', 'Raul Erasmo Chandia Zuñiga', 'Roto Chileno Sitio N 19 Dpto 2 Villa 3', 'Talagante', true),
('78129079-3', 'Transporte De Carga Venegas Y Otro Limitada', 'Fernando Antonio Venegas Sandoval', 'CALLEJÓN BUSTAMANTE 000 SECTOR LAS CHILCAS', 'Chillan', true),
('77502623-5', 'TRANSPORTE FRANCISCO OYANADEL RAMOS SPA', 'Francisco Javier Oyanadel Ramos', 'PJE FLOR DEL COBRE 5344 LA FLORIDA ETAPA IV', 'La Serena', true),
('78001651-5', 'TRANSPORTE J Y D VERDEJO SPA', 'DIEGO MAURICIO VERDEJO ROBLES', 'RIGOLEMO 00 MALLOA', 'Malloa', true),
('78099333-2', 'Transporte Js Spa', 'Juan Rodolfo Soto Zuñiga', 'Davila Rodriiguez Lote 2 Los Marcos San Francisco De Mostazal', 'San FcoMostazal', true),
('77505286-4', 'Transporte Matisaurio Spa', 'Matias Jose Rubio Galaz', 'Lt 4 De St Pp San Juan La Hacienda Olivar', 'Olivar', true),
('77496396-0', 'Transporte Nelson Rodomir Sepulveda E.i.r.l.', 'Sepulveda Nelson', 'Nuevos Campos 8850 Lta 2 Silos De Tunca Graneros', 'Graneros', true),
('77642747-0', 'Transporte Santa Elena Spa', 'Juan Bautista Amaya Figueroa', 'Mz E Lt 6 Lora Lora', 'Licanten', true),
('76851961-7', 'Transporte Y Arriendo De Camion Pablo Cesar Silva San Martin Spa', 'Pablo Cesar Silva San Martin', 'Independencia 646', 'Tucapel', true),
('78365117-3', 'Transportes Almendra Y Roco Spa', 'HUGOLINO OSCAR D''APREMONT FUENTES', 'VICTOR CUCCUINI 139', 'Recoleta', true),
('77656577-6', 'Transportes Cristina Aguirre Spa', 'Cristina Adriana Aguirre Sobrecuevas', 'Sgto. Aldea 906', 'Padre Hurtado', true),
('77974457-4', 'Transportes Arlette Spa', 'Jaime Ismael Astroza Rodríguez', 'Carmen Covarrubias 32 Of 512 Nunoa', 'Santiago', true),
('77965304-8', 'Transportes De Carga Hernan Segundo Cabrera Avila E.i.r.l', 'Hernan Segundo Cabrera Avila', 'Luis Mayol 001 Poblacion Padre Hurtado', 'Chimbarongo', true),
('77949497-7', 'TRANSPORTES KAISER SPA', 'Hector Rodrigo Garcia Quintana', 'Paseo Huerfanos 1055 503', 'Santiago', true),
('77374557-9', 'Transportes Carlos  González Loyola E.i.r.l.', 'Carlos Alberto Gonzalez Loyola', 'Salvador Allende 32 Pedro Aguirre Cerda', 'Puente Alto', true),
('77890332-6', 'Transportes Carlos Castillo Miñano E.i.r.l.', 'Carlos Alberto Castillo Miñano', 'Pje Volc Marmolejo 840 D- 2 Valle Norte Iv Lampa', 'Lampa', true),
('76826483-K', 'Transportes Carlos Rene Cornejo Molina E.i.r.l.', 'Carlos Rene Cornejo Molina', 'Pasaje Creta, Villa Parque Industrial 662', 'Talagante', true),
('78132030-7', 'Transportes Claudio Painequeo E.i.r.l.', 'Claudio Alejandro Painequeo Concha', 'Jose Tomas Ovalle 143 Talagante', 'Talagante', true),
('77373865-3', 'Transportes Claudio Vilogron Paredes E.i.r.l.', 'Claudio Antonio Dionisio Vilogron Paredes', 'P Valdivia 182 America I', 'Paine', true),
('77489241-9', 'Transportes Cruz Spa', 'Eduardo Felipe Cruz Molina', 'EL OLIMPO 1528 V EL OLIMPO NULL', 'Maipu', true),
('77569357-6', 'Transportes De Carga  Cya  Spa', 'Jorge Humberto Castillo Perez', 'Panamericana sur km 41 parcela 114', 'Paine', true),
('76987117-9', 'Transportes De Carga Magaly Rocio Añorga Huerta E.i.r.l.', 'Magaly Rocio Añorga Huerta', 'QUEMCHI 5836 ROBERT KENNEDY', 'ESTACION CENTRAL', true),
('76977185-9', 'Transportes Eduardo Alarcon Empresa Individual De Responsabilidad Li', 'Eduardo Benjamin Alarcon Espinoza', 'Los Claveles 1451 Villa El Bosque', 'Quinchao', true),
('77377507-9', 'Transportes Eric Darat E.i.r.l.', 'Eric Henry Darat Ramirez', 'Pasaje Tarragona 1486 V Galilea F 1', 'Curico', true),
('78089406-7', 'Transportes Evem Spa', 'Veronica Del Pilar Panes Lopez', 'Lalo Parra 16 Lt 10 -m 10 Bicentenario Cabrero', 'Cabrero', true),
('77849029-3', 'Transportes Expresso Ignacio Spa', 'JESSICA IDA PLAZA PLAZA', 'Hij La Chunga Lote 92 Null', 'La Serena', true),
('77401233-8', 'Transportes Felipe Andres Rex Villalobos E.i.r.l.', 'Felipe Andres Rex Villalobos', 'General Jose Villagra 8086 33 Lo Prado', 'Lo Prado', true),
('77375352-0', 'Transportes Fernando Darat Candia E.i.r.l.', 'Fernando Edinson Darat Candia', 'V Cordillera Pj 6 516 LT 1 B', 'San Clemente', true),
('77032978-7', 'TRANSPORTES FLOR VALLADARES SPA', 'Flor Del Carmen Valladares Lopez', 'PINTOR JUAN FRANCISCO GON 343 ILUSIONES COMPARTIDA MELIPILLA', 'Santiago', true),
('78027318-6', 'TRANSPORTES GERMAN EDUARDO PARDO ANTIHUAL E.I.R.L', 'German Eduardo Pardo Antihual', 'GUARDIA VIEJA 202 OF 403 4P PROVIDENCIA', 'Santiago', true),
('77499811-K', 'Transportes Jahdiel Spa', 'Marco Antonio Sanhueza Espino', 'Avda Chile 14', 'San Bernardo', true),
('77495891-6', 'TRANSPORTES JHON EDWARD CHAVARRIA MUÑOZ E.I.R.L', 'Jhon Chavarria Muñoz', 'Los Maitenes s/n volcan', 'Vilcun', true),
('78283626-9', 'Transportes Jkarimv Spa', 'JAMYR AJMED KARIM VARGAS', 'REGIMIENTO COQUIMBO 060 PARTE ALTA NULL', 'Coquimbo', true),
('77377829-9', 'TRANSPORTES JOSE MIGUEL ALARCON SpA', 'Jose Miguel Alarcon Aguilera', 'Panamericana sur km 41 parcela 114', 'Paine', true),
('78057959-5', 'Transportes Jota Castillo Spa', 'Jose Felix Castillo Oyarzo', 'Pje Gilberto Rojas 2258 B Del Boldo 4 Curico', 'Curico', true),
('77992492-0', 'TRANSPORTES JUAN AGUILAR VALENZUELA EIRL', 'Juan German Aguilar Valenzuela', 'PJE IRMA OYARZO 77 JOSE M CARRERA 2', 'Santiago', true),
('76903711-K', 'Transportes Jyr Spa', 'Luis Hernan Jara Gonzalez', 'Pasaje Rio Yelcho 188 Villa Los Ríos', 'Panguipulli', true),
('76507104-6', 'TRANSPORTES LOS ALAMOS LIMITADA', 'Andres Fernando Cardenas Neira', 'CALLE LA VENDIMIA 1322 VILLA LOS ALAMOS', 'Padre Hurtado', true),
('77389829-4', 'Transportes Manuel  Perez Vilches E.i.r.l.', 'Manuel Natalio Pérez Vilches', 'Pj a blest gana 0379 ST 202 belgica', 'La Granja', true),
('77672752-0', 'Transportes Mauricio Lastra Azocar E.i.r.l', 'Mauricio Eduardo Lastra Azocar', 'LA GRANJA PC 16 LOTE 2-B RETIRO', 'Retiro', true),
('77400529-3', 'Transportes Miguel Angel Sepulveda Verdugo Spa', 'Miguel Angel Sepulveda Verdugo', '17 Med pte 0923 Jardin del Valle', 'Talca', true);

-- Sync all to transportistas if not already there
INSERT INTO transportistas (rut, razon_social, nombre_fantasia, direccion, is_active)
SELECT rut, razon_social, nombre_contacto, direccion, is_active FROM subcontratistas
ON CONFLICT (rut) DO NOTHING;

SELECT COUNT(*) as subcontratistas_loaded FROM subcontratistas;
SELECT COUNT(*) as transportistas_total FROM transportistas;
